# -*- coding: utf-8 -*-
"""P2_Ej1_ADG

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBNvSYb-htBL4Hvxz8IXqAr1a9onjNWj
"""

# P2_Ej1_ADG.py
# Autor: Alejandra Díaz González
# Descripción: Calcula comisiones de vendedores según nivel de ventas

import math

# Función para calcular comisión y nivel
def calcular_comision(monto_venta):
    """
    Recibe el monto de venta y retorna (comisión, nivel)
    """
    if monto_venta < 1000:
        comision = monto_venta * 0.05
        nivel = "Bronce"
    elif monto_venta <= 5000:
        comision = monto_venta * 0.10
        nivel = "Plata"
    else:
        comision = monto_venta * 0.15
        nivel = "Oro"

    # Redondear a 2 decimales
    comision = round(comision, 2)
    return comision, nivel

# Menú principal
def main():
    while True:
        print("\n--- Menú Principal ---")
        print("1. Calcular Comisión")
        print("2. Salir")

        opcion = input("Seleccione una opción (1 o 2): ")

        if opcion == "1":
            # Solicitar nombre del vendedor
            nombre = input("Nombre del vendedor: ")

            # Validar monto (número positivo)
            while True:
                try:
                    monto = float(input("Monto total vendido en el mes: $"))
                    if monto > 0:
                        break
                    else:
                        print("Error: el monto debe ser un número positivo.")
                except ValueError:
                    print("Error: ingrese un número válido.")

            # Calcular comisión y nivel
            comision, nivel = calcular_comision(monto)
            total_recibir = round(monto + comision, 2)

            # Mostrar resultados
            print("\n--- Resultados ---")
            print(f"Vendedor: {nombre}")
            print(f"Monto vendido: ${monto:.2f}")
            print(f"Nivel: {nivel}")
            print(f"Comisión: ${comision:.2f}")
            print(f"Total a recibir (venta + comisión): ${total_recibir:.2f}")

        elif opcion == "2":
            print("¡Gracias por usar el programa! Hasta luego.")
            break

        else:
            print("Opción no válida. Por favor, seleccione 1 o 2.")

# Ejecutar el programa
if __name__ == "__main__":
    main()